version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    port: 
      - "3000:3000"
    volumes: 
      - /app/node_module
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_module
      - .:/app
    command: ["npm", "run", "test"]

